### ISSUE TITLE
[imgprocessor] chessboard squares detection

### ISSUE THREAD

**Issue by superwhoopy** [superwhoopy/chessreader#2]
* isolate the 64 squares of the chessboard using contour detection
* should work even if the image is slightly tilted?

**Comment by daniel-ohayon** [comment]
Detecting the 64 squares seems fairly robust using a Hough line detector (cf. branch `image-recognition`) ; current procedure:
1. canny transform to convert image into BW image of the edges
2. perform Hough line detection, and isolate the 9 most significant lines at an angle close enough to 0 and 90 degrees
3. compute intersections of the Hough lines and isolate the 64 squares

This approach has 2 limits: it requires the image to be fairly straight, and the cases on the border may have a different structure than the inner cases (e.g. include the border of the chessboard with the numbers/letters drawn on it, etc.)
The tilting problem could be addressed by searching for 2 sets of 9+9 orthogonal lines in the image, as opposed to lines at 0 and 90 degrees.

**Comment by superwhoopy** [comment]
I suggest we close the issue at this time; further improvements will come later.
